// LOCALHOST

////////////////////// RESTAURANT /////////////
### Get all restaurant
GET http://localhost:3000/restaurants

### Get restaurant by id
GET http://localhost:3000/restaurants/6470f7b954a09fdbf30cf7e8

### Create restaurant
POST http://localhost:3000/restaurants HTTP/1.1
content-type: application/json

{
        "name": "Restaurant 3",
        "description": "Restaurant 3 Description",
        "phone_number": "+12 345 6789",
        "opening_hours": "6am - 10pm",
        "average_rating": "5 stars",
        "menu_id": "646f7a47f3c0b6aa6b2be7b9"
}


### PUT restaurant
PUT http://localhost:3000/restaurants/6476d5a3704e47faec3f5c2e HTTP/1.1
content-type: application/json

{
        "name": "Restaurant 4",
        "description": "Restaurant 4 Description",
        "phone_number": "+12 345 6789",
        "opening_hours": "6am - 10pm",
        "average_rating": "3 stars",
        "menu_id": "646f79d0f3c0b6aa6b2be7b7"
}

### DELETE restaurant
DELETE http://localhost:3000/restaurants/6476d5a3704e47faec3f5c2e HTTP/1.1

//////////////////////// MENU /////////////////////

### Get all menu
GET http://localhost:3000/menu

### Get menu by id
GET http://localhost:3000/menu/6476d7bb33bf02f5b0bb30b6

### Create menu
POST http://localhost:3000/menu HTTP/1.1
content-type: application/json

{
        "name": "Breakfast Menu 1",
        "description": "Breakfast Menu 1 Description",
        "restaurant_id": "646f79d0f3c0b6aa6b2be7b7"
}


### PUT menu
PUT http://localhost:3000/menu/646f7a47f3c0b6aa6b2be7b9 HTTP/1.1
content-type: application/json

{
        "name": "Breakfast Menu 3",
        "description": "Breakfast Menu 3 Description",
        "restaurant_id": "646f79d0f3c0b6aa6b2be7b7"
}

### DELETE menu
DELETE http://localhost:3000/menu/646f7a47f3c0b6aa6b2be7b9 HTTP/1.1

//////////////////////// USERS /////////////////////

### Get all user
GET http://localhost:3000/users

### Get user by id
GET http://localhost:3000/users/6476e0fe881655f95ebf0750

### Create user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
        "firstName": "John",
        "lastName": "Doe",
        "email": "johndoe@example.com",
        "birthday": "1990-01-01"
}


### PUT user
PUT http://localhost:3000/users/6476e292a9303d376f463c93 HTTP/1.1
content-type: application/json

{
        "firstName": "Betty",
        "lastName": "Doe",
        "email": "bettydoe@example.com",
        "birthday": "1990-01-01"
}

### DELETE user
DELETE http://localhost:3000/users/6476e292a9303d376f463c93 HTTP/1.1


//////////////////////// ITEMS /////////////////////

### Get all items
GET http://localhost:3000/items

### Get item by id
GET http://localhost:3000/items/6476e468881655f95ebf0752

### Create item
POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
        "name": "Item 1",
        "description": "Item Description",
        "price": "$1",
        "menu_id": "646f7a47f3c0b6aa6b2be7b9"
}


### PUT item
PUT http://localhost:3000/items/6476e56f02ed0345a7e07415 HTTP/1.1
content-type: application/json

{
        "name": "Item 2",
        "description": "Item 2 Description",
        "price": "$1",
        "menu_id": "646f7a47f3c0b6aa6b2be7b9"
}

### DELETE item
DELETE http://localhost:3000/items/6476e56f02ed0345a7e07415 HTTP/1.1
