// LOCALHOST
### Get all restaurant
GET http://localhost:3000/restaurants

### Get restaurant by id
GET http://localhost:3000/restaurants/646f79d0f3c0b6aa6b2be7b7

### Create restaurant
POST http://localhost:3000/restaurants HTTP/1.1
content-type: application/json

{
        "name": "Restaurant 3",
        "description": "Restaurant 3 Description",
        "phone_number": "+12 345 6789",
        "opening_hours": "6am - 10pm",
        "average_rating": "5 stars",
        "menu_id": "646f7a47f3c0b6aa6b2be7b9"
}


### PUT restaurant
PUT http://localhost:3000/restaurants/6470fac1bc382e628223c9a1 HTTP/1.1
content-type: application/json

{
        "name": "Restaurant 4",
        "description": "Restaurant 4 Description",
        "phone_number": "+12 345 6789",
        "opening_hours": "6am - 10pm",
        "average_rating": "3 stars",
        "menu_id": "646f79d0f3c0b6aa6b2be7b7"
}

### DELETE restaurant
DELETE http://localhost:3000/restaurants/6470fac1bc382e628223c9a1 HTTP/1.1
